name: Build Mod

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          combine: true

  package:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: geode-sdk/build-geode-mod/combine@main
        id: combined

      - uses: actions/upload-artifact@v4
        with:
          name: Build Output
          path: ${{ steps.combined.outputs.build-output }}
